{
  "formatVersion": "1.1",
  "component": {
    "group": "architectury-plugin",
    "module": "architectury-plugin.gradle.plugin",
    "version": "3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "architectury-plugin.gradle.plugin-3.4-SNAPSHOT.jar",
          "url": "architectury-plugin.gradle.plugin-3.4-SNAPSHOT.jar",
          "size": 153021,
          "sha512": "4f8703237c6eb16a75d48ea0e7e64fb6c744aa7ef610d9c140bfec76e26e26f1985b232c12a206733e4fb3ad5370bec81c8415d5ed6e8fff0115855bf47a272e",
          "sha256": "6dc8d1e4f534092d6ae03594eb9c9b76a9bb1764034a02f3a4bbe5049b864a2a",
          "sha1": "b12b5ed1d0fa2121b1c53f0111ad9ed6af693b78",
          "md5": "4427195786d6f1a702d26f4c01f890f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext",
          "module": "gradle-idea-ext",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-transformer",
          "version": {
            "requires": "5.2.87"
          }
        },
        {
          "group": "dev.architectury",
          "module": "tiny-remapper",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "architectury-plugin.gradle.plugin-3.4-SNAPSHOT.jar",
          "url": "architectury-plugin.gradle.plugin-3.4-SNAPSHOT.jar",
          "size": 153021,
          "sha512": "4f8703237c6eb16a75d48ea0e7e64fb6c744aa7ef610d9c140bfec76e26e26f1985b232c12a206733e4fb3ad5370bec81c8415d5ed6e8fff0115855bf47a272e",
          "sha256": "6dc8d1e4f534092d6ae03594eb9c9b76a9bb1764034a02f3a4bbe5049b864a2a",
          "sha1": "b12b5ed1d0fa2121b1c53f0111ad9ed6af693b78",
          "md5": "4427195786d6f1a702d26f4c01f890f5"
        }
      ]
    }
  ]
}
