{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "installertools",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "bgwgqwlqmrfxtdmpcgxvtvntsy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "installertools-1.2.0.jar",
          "url": "installertools-1.2.0.jar",
          "size": 61543,
          "sha512": "f6e76ce6e7ee4f899f267ed2cf68435171acb0e3e418bb5dccb5cb6ddca780d1ac76a52dd31f38fb09d1268c87cbf4424109e7b32f9c7d6172f5d57333e7483e",
          "sha256": "e1f31d6e2272f29dfb08739721c150b0021d789a580b821515c1a8a782f42fcc",
          "sha1": "3f0d191d0f13e58e63beb01ba2e69355718f03da",
          "md5": "15a2b845202368bdb80d20dda46ae16f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "net.md-5",
          "module": "SpecialSource",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "installertools-1.2.0.jar",
          "url": "installertools-1.2.0.jar",
          "size": 61543,
          "sha512": "f6e76ce6e7ee4f899f267ed2cf68435171acb0e3e418bb5dccb5cb6ddca780d1ac76a52dd31f38fb09d1268c87cbf4424109e7b32f9c7d6172f5d57333e7483e",
          "sha256": "e1f31d6e2272f29dfb08739721c150b0021d789a580b821515c1a8a782f42fcc",
          "sha1": "3f0d191d0f13e58e63beb01ba2e69355718f03da",
          "md5": "15a2b845202368bdb80d20dda46ae16f"
        }
      ]
    }
  ]
}
