{
  "formatVersion": "1.1",
  "component": {
    "group": "com.electronwill.night-config",
    "module": "toml",
    "version": "3.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "toml-3.8.2.jar",
          "url": "toml-3.8.2.jar",
          "size": 39516,
          "sha512": "f21dbf268c3aab4dd24a1edd26894b24d8246bfa7756fad88ed3c30a4b9ddb545e0af8671b0b2b5871e6fca8aca1f09309f8ce0abdfe1d46b6b74f90461a471d",
          "sha256": "7e9aa218d9ed156fb6c621a4a3c66bef3a7ec351757527590aa994d019bb36fd",
          "sha1": "c128842f759692f613ea6c3ef0ef052273bbb38c",
          "md5": "9bc7366ba0f0f364b3d9d1fcd853b235"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "toml-3.8.2.jar",
          "url": "toml-3.8.2.jar",
          "size": 39516,
          "sha512": "f21dbf268c3aab4dd24a1edd26894b24d8246bfa7756fad88ed3c30a4b9ddb545e0af8671b0b2b5871e6fca8aca1f09309f8ce0abdfe1d46b6b74f90461a471d",
          "sha256": "7e9aa218d9ed156fb6c621a4a3c66bef3a7ec351757527590aa994d019bb36fd",
          "sha1": "c128842f759692f613ea6c3ef0ef052273bbb38c",
          "md5": "9bc7366ba0f0f364b3d9d1fcd853b235"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "toml-3.8.2-javadoc.jar",
          "url": "toml-3.8.2-javadoc.jar",
          "size": 27434,
          "sha512": "273678ebf51b60ef1b97a8bc3f8804df0f5f220cdde8a26ef845791e4b27409c3ac447b36864a2771609891b42ad2402d7cf73d8b48491f2c6e50b5ec408913d",
          "sha256": "12d8916da7c3a18fdeb4db30b3d0fe563c960a1ca87456b0e809495bd8649689",
          "sha1": "150dc407bbf5edad900a6138b1b44b45ccb36a52",
          "md5": "90ebd56009b598ae5cd8e7e26ecc14ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "toml-3.8.2-sources.jar",
          "url": "toml-3.8.2-sources.jar",
          "size": 22621,
          "sha512": "0ef7b728c3f634705049e6b3a113902ec8e0e76c2282bda9b8444a801d1dc07f50766b4abde324fd8ba667d2ad79fb9897d24372a1934783ffb76333b83f5df4",
          "sha256": "80b132dc5299e0dfa58cf5ee4737396e47b7bdc5b8943c014a3e46028d2f8f53",
          "sha1": "31a41cf052f9d386926580839bc2785a867d3b6a",
          "md5": "ebdb928679a4929599a0b2b6cc05f6e5"
        }
      ]
    }
  ]
}
