{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.9.0/kotlinx-serialization-cbor-1.9.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.9.0.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.9.0.jar",
          "size": 65913,
          "sha512": "44e575c677c652dbf66332a32ded1b40fc45968bee035f728ab9c5ebacb49260776e91305b0eb665f48f1d817c9a43888a436b35c7959c086241ba0c51ceeedb",
          "sha256": "e45f32f0d80e1164593cfcf9f1907ae39871084c6aa08e49acc2e8e22e1d93ce",
          "sha1": "a5b382b72c6f51ff6129080c49c4ae4c12ff57a6",
          "md5": "339c6be50c89fcadaa92e4d98d7a4216"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.9.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.9.0.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.9.0.jar",
          "size": 65913,
          "sha512": "44e575c677c652dbf66332a32ded1b40fc45968bee035f728ab9c5ebacb49260776e91305b0eb665f48f1d817c9a43888a436b35c7959c086241ba0c51ceeedb",
          "sha256": "e45f32f0d80e1164593cfcf9f1907ae39871084c6aa08e49acc2e8e22e1d93ce",
          "sha1": "a5b382b72c6f51ff6129080c49c4ae4c12ff57a6",
          "md5": "339c6be50c89fcadaa92e4d98d7a4216"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.9.0-sources.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.9.0-sources.jar",
          "size": 24260,
          "sha512": "1b423ebdb87a0175c49f2381dff5c5c4bb676497bcaf2d0c76326c151a92715e042d2a30d99f310ac8897dc1d08b3a21c5731efd5df3d284ca19cfaafa54bf0e",
          "sha256": "aaf83c4c7e24060608bff3f7279b0f543b21ed1544103bdfebbcb88adb7021cd",
          "sha1": "58445b5ca679559d7e55a249cec9a2f3605056c8",
          "md5": "c48b921acf26761316d5b7621f1e3eaa"
        }
      ]
    }
  ]
}
