{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-datetime/0.7.1/kotlinx-datetime-0.7.1.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-datetime",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-datetime-jvm-0.7.1.jar",
          "url": "kotlinx-datetime-jvm-0.7.1.jar",
          "size": 694336,
          "sha512": "1c7f560ae5ea82f5e874ebd517b44083a66556c821a5fb58216561568a97fc314355e81f5cf1940d6b67dfbb179c3191b59fc4252c11ba9de21ea3433ca27311",
          "sha256": "3b8b98657c9aff3be7f6b4b575e9f3fb9a3a1f452a801da0f438901734acdade",
          "sha1": "81c2e0246bd28cc2dcbdf0ab53628322e66a9de9",
          "md5": "70b404e22ebc7eebfa53f7d1941af072"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-datetime-jvm-0.7.1.jar",
          "url": "kotlinx-datetime-jvm-0.7.1.jar",
          "size": 694336,
          "sha512": "1c7f560ae5ea82f5e874ebd517b44083a66556c821a5fb58216561568a97fc314355e81f5cf1940d6b67dfbb179c3191b59fc4252c11ba9de21ea3433ca27311",
          "sha256": "3b8b98657c9aff3be7f6b4b575e9f3fb9a3a1f452a801da0f438901734acdade",
          "sha1": "81c2e0246bd28cc2dcbdf0ab53628322e66a9de9",
          "md5": "70b404e22ebc7eebfa53f7d1941af072"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-datetime-jvm-0.7.1-sources.jar",
          "url": "kotlinx-datetime-jvm-0.7.1-sources.jar",
          "size": 143046,
          "sha512": "d23f981e99660765667c9104958391abcb1f1a0268e161e993eb2a632fd6a1ae2d2528d7048dc04d7f8926fa02a34e5eaed001cbf0b262100354096e7985e942",
          "sha256": "7252432e626821da49ae6ba9bf6880988ee9e9977ba6fdcd4e225c57cd387f2f",
          "sha1": "62e1b01b1d8a8e136fd7c8f2ab544500d734b853",
          "md5": "a6f0b5c4232a775c1bf8e02a3e28ea0b"
        }
      ]
    }
  ]
}
