{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.installertools",
    "module": "cli-utils",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cli-utils-2.1.2.jar",
          "url": "cli-utils-2.1.2.jar",
          "size": 9379,
          "sha512": "ab40da229fb1403625c0b4d4317d2ad903b2190a4a2ddfbf353ab410ecc0b71401ae6e7f96172030b35f202e4d0f8b05ae264709c2606424035be398f7d10270",
          "sha256": "023a5a0cc7579fbf10a0bdd2a47a8ac1a10046a6432fef36ec850ab1ccf5504d",
          "sha1": "e5a3115eb9e299117472675946be8a72e4990ad6",
          "md5": "5259159c1f29cb3c532e381601933602"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cli-utils-2.1.2.jar",
          "url": "cli-utils-2.1.2.jar",
          "size": 9379,
          "sha512": "ab40da229fb1403625c0b4d4317d2ad903b2190a4a2ddfbf353ab410ecc0b71401ae6e7f96172030b35f202e4d0f8b05ae264709c2606424035be398f7d10270",
          "sha256": "023a5a0cc7579fbf10a0bdd2a47a8ac1a10046a6432fef36ec850ab1ccf5504d",
          "sha1": "e5a3115eb9e299117472675946be8a72e4990ad6",
          "md5": "5259159c1f29cb3c532e381601933602"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cli-utils-2.1.2-sources.jar",
          "url": "cli-utils-2.1.2-sources.jar",
          "size": 4811,
          "sha512": "6035488007f7d5605d9c4873e152a6e78deff4c61da66343140197c4c85c25732cdde1c8396ccde3f8cb9386160031f871faaf8ba4ebd0c7230a0ba78f04f4a1",
          "sha256": "f672889289cc4ec58d5a642594c0d57c928b20d3273e98a958adfc4fa69370ff",
          "sha1": "5d4755218f066ee041ce13e244b82be425141232",
          "md5": "0db1b2407d4e861a9a32b6f4577a8f54"
        }
      ]
    }
  ]
}
