{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.accesstransformers",
    "module": "at-modlauncher",
    "version": "10.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "10.1.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jopt-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "at-modlauncher-10.0.1.jar",
          "url": "at-modlauncher-10.0.1.jar",
          "size": 2347,
          "sha512": "a8c830227efa436bccf4b70699c36e0b8daa6caaa404955c05a4f003f2b7cb1d8dd5fffd5a827c4e716dbc64d918fe5ea47800767c07ef0695afbafb6d5badf7",
          "sha256": "2a4b447c6944a2b89e383c1eed9a26bb5cc60330a5bb26ef0a912a38d52df935",
          "sha1": "5aba50202aceead086bc09fbc2751c9f05cb4890",
          "md5": "f65434f122b97b1ac8fe56ff54873b5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "10.1.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jopt-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "at-modlauncher-10.0.1.jar",
          "url": "at-modlauncher-10.0.1.jar",
          "size": 2347,
          "sha512": "a8c830227efa436bccf4b70699c36e0b8daa6caaa404955c05a4f003f2b7cb1d8dd5fffd5a827c4e716dbc64d918fe5ea47800767c07ef0695afbafb6d5badf7",
          "sha256": "2a4b447c6944a2b89e383c1eed9a26bb5cc60330a5bb26ef0a912a38d52df935",
          "sha1": "5aba50202aceead086bc09fbc2751c9f05cb4890",
          "md5": "f65434f122b97b1ac8fe56ff54873b5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "at-modlauncher-10.0.1-sources.jar",
          "url": "at-modlauncher-10.0.1-sources.jar",
          "size": 1689,
          "sha512": "777d4f724c4734cd6e73e1db5ccca50819c630331b21994744458e268dcb64fb51ddf99821cb1f54a371308d1403e77f06578491ae0f96d2a2d2c28797f5eae9",
          "sha256": "4f23566bb1e9a6cb1250a564ea337ab984c69daf54d7e304515b7002c479fcca",
          "sha1": "14efd42caf0e62134fe03c4460c18741e34909cd",
          "md5": "9e6a41fa120c0a56bd8103302660f9e3"
        }
      ]
    }
  ]
}
