{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged.fancymodloader",
    "module": "earlydisplay",
    "version": "4.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "earlydisplay-4.0.40.jar",
          "url": "earlydisplay-4.0.40.jar",
          "size": 261718,
          "sha512": "cf8efb054dff3c64a10887bb5d409fc53a06db237d3fcc621a24ec7a63a219fbf03946335b28949873c47d06a0691b1a15f4059e0402047ac83c6989534cd01b",
          "sha256": "57ad2512412d491ab761125c27f950dec6f14cd8639a886a21d069fb991b6a02",
          "sha1": "a91508c15e097b9557ac81954ae1593e3bcd2b93",
          "md5": "5acd575eb4b795d511de1755b43b8805"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "4.0.40"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-tinyfd",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "earlydisplay-4.0.40.jar",
          "url": "earlydisplay-4.0.40.jar",
          "size": 261718,
          "sha512": "cf8efb054dff3c64a10887bb5d409fc53a06db237d3fcc621a24ec7a63a219fbf03946335b28949873c47d06a0691b1a15f4059e0402047ac83c6989534cd01b",
          "sha256": "57ad2512412d491ab761125c27f950dec6f14cd8639a886a21d069fb991b6a02",
          "sha1": "a91508c15e097b9557ac81954ae1593e3bcd2b93",
          "md5": "5acd575eb4b795d511de1755b43b8805"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "earlydisplay-4.0.40-sources.jar",
          "url": "earlydisplay-4.0.40-sources.jar",
          "size": 229835,
          "sha512": "8935f7653451b601bccdbe8e02d9a2be946ddb3f2d2c54ce78fa039a2b8a66489c3b704a433cbed0f4a25aed65412c9229533fe55df009e2bbc448dab30d07cf",
          "sha256": "7fa0fff96df2d39456d7fb168c71e66aecd3c3316eb8aef6092592100633411c",
          "sha1": "42ee5b0e4827d79df7752f2deb5eaa137dcc955f",
          "md5": "14148cdaa6ac6a3d2f38a6c25e749107"
        }
      ]
    }
  ]
}
