{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-io-bytestring",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-bytestring-metadata-0.8.0.jar",
          "url": "kotlinx-io-bytestring-0.8.0.jar",
          "size": 9481,
          "sha512": "46c69473cb5974d837801f345ab4506e6092743d30bf7d00c0ed9179c51c6fcdaabd434b96d665e715b6ed9517d52e93b88a8a9046549ece4a8461db005768f6",
          "sha256": "8349804cf59bb0e855399d02f7bdbea1104a428e33777e971bf31d1bbd250d3f",
          "sha1": "e27c16b847a8bb1380c69bbf5fb7423c9bfc2fa8",
          "md5": "321a6424e071b98d2a8ca932d77db72e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-io-bytestring-kotlin-0.8.0-sources.jar",
          "url": "kotlinx-io-bytestring-0.8.0-sources.jar",
          "size": 12597,
          "sha512": "57ff200c25acc3311c8a5f96eefad0830547d8060215c5a1f7d8ab7093c9b9121a30d34d1ccbd8c7e06805af6f3bc74b925cf75dbef7e2257cab8336b544420e",
          "sha256": "3d5c0dfcfdd60610c5facf5d7b54398264e7473d16f39d87f72e758d4aadf8b9",
          "sha1": "896f572a48b02496d6b37af8ea9da335866a23ca",
          "md5": "708f8f215cabbb48101b67eafb6ac9c6"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativearm32/0.8.0/kotlinx-io-bytestring-androidnativearm32-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativearm32",
        "version": "0.8.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativearm32/0.8.0/kotlinx-io-bytestring-androidnativearm32-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativearm32",
        "version": "0.8.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativearm64/0.8.0/kotlinx-io-bytestring-androidnativearm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativearm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativearm64/0.8.0/kotlinx-io-bytestring-androidnativearm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativearm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativex64/0.8.0/kotlinx-io-bytestring-androidnativex64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativex64",
        "version": "0.8.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativex64/0.8.0/kotlinx-io-bytestring-androidnativex64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativex64",
        "version": "0.8.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativex86/0.8.0/kotlinx-io-bytestring-androidnativex86-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativex86",
        "version": "0.8.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-androidnativex86/0.8.0/kotlinx-io-bytestring-androidnativex86-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-androidnativex86",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosarm64/0.8.0/kotlinx-io-bytestring-iosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosarm64/0.8.0/kotlinx-io-bytestring-iosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosarm64/0.8.0/kotlinx-io-bytestring-iosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iossimulatorarm64/0.8.0/kotlinx-io-bytestring-iossimulatorarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iossimulatorarm64/0.8.0/kotlinx-io-bytestring-iossimulatorarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iossimulatorarm64/0.8.0/kotlinx-io-bytestring-iossimulatorarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosx64/0.8.0/kotlinx-io-bytestring-iosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosx64/0.8.0/kotlinx-io-bytestring-iosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-iosx64/0.8.0/kotlinx-io-bytestring-iosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-js/0.8.0/kotlinx-io-bytestring-js-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-js/0.8.0/kotlinx-io-bytestring-js-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-js/0.8.0/kotlinx-io-bytestring-js-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-jvm/0.8.0/kotlinx-io-bytestring-jvm-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-jvm",
        "version": "0.8.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-jvm/0.8.0/kotlinx-io-bytestring-jvm-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-jvm",
        "version": "0.8.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-jvm/0.8.0/kotlinx-io-bytestring-jvm-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-jvm",
        "version": "0.8.0"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxarm32hfp/0.8.0/kotlinx-io-bytestring-linuxarm32hfp-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxarm32hfp",
        "version": "0.8.0"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxarm32hfp/0.8.0/kotlinx-io-bytestring-linuxarm32hfp-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxarm32hfp",
        "version": "0.8.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxarm64/0.8.0/kotlinx-io-bytestring-linuxarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxarm64/0.8.0/kotlinx-io-bytestring-linuxarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxx64/0.8.0/kotlinx-io-bytestring-linuxx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-linuxx64/0.8.0/kotlinx-io-bytestring-linuxx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-linuxx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosarm64/0.8.0/kotlinx-io-bytestring-macosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosarm64/0.8.0/kotlinx-io-bytestring-macosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosarm64/0.8.0/kotlinx-io-bytestring-macosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosx64/0.8.0/kotlinx-io-bytestring-macosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosx64/0.8.0/kotlinx-io-bytestring-macosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-macosx64/0.8.0/kotlinx-io-bytestring-macosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-macosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-mingwx64/0.8.0/kotlinx-io-bytestring-mingwx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-mingwx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-mingwx64/0.8.0/kotlinx-io-bytestring-mingwx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-mingwx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosarm64/0.8.0/kotlinx-io-bytestring-tvosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosarm64/0.8.0/kotlinx-io-bytestring-tvosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosarm64/0.8.0/kotlinx-io-bytestring-tvosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvossimulatorarm64/0.8.0/kotlinx-io-bytestring-tvossimulatorarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvossimulatorarm64/0.8.0/kotlinx-io-bytestring-tvossimulatorarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvossimulatorarm64/0.8.0/kotlinx-io-bytestring-tvossimulatorarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosx64/0.8.0/kotlinx-io-bytestring-tvosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosx64/0.8.0/kotlinx-io-bytestring-tvosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-tvosx64/0.8.0/kotlinx-io-bytestring-tvosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-tvosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-js/0.8.0/kotlinx-io-bytestring-wasm-js-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-js/0.8.0/kotlinx-io-bytestring-wasm-js-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-js/0.8.0/kotlinx-io-bytestring-wasm-js-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-js",
        "version": "0.8.0"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-wasi/0.8.0/kotlinx-io-bytestring-wasm-wasi-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-wasi",
        "version": "0.8.0"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-wasi/0.8.0/kotlinx-io-bytestring-wasm-wasi-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-wasi",
        "version": "0.8.0"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-wasm-wasi/0.8.0/kotlinx-io-bytestring-wasm-wasi-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-wasm-wasi",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm32/0.8.0/kotlinx-io-bytestring-watchosarm32-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm32",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm32/0.8.0/kotlinx-io-bytestring-watchosarm32-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm32",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm32/0.8.0/kotlinx-io-bytestring-watchosarm32-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm32",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm64/0.8.0/kotlinx-io-bytestring-watchosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm64/0.8.0/kotlinx-io-bytestring-watchosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosarm64/0.8.0/kotlinx-io-bytestring-watchosarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosdevicearm64/0.8.0/kotlinx-io-bytestring-watchosdevicearm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosdevicearm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosdevicearm64/0.8.0/kotlinx-io-bytestring-watchosdevicearm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosdevicearm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosdevicearm64/0.8.0/kotlinx-io-bytestring-watchosdevicearm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosdevicearm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchossimulatorarm64/0.8.0/kotlinx-io-bytestring-watchossimulatorarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchossimulatorarm64/0.8.0/kotlinx-io-bytestring-watchossimulatorarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchossimulatorarm64/0.8.0/kotlinx-io-bytestring-watchossimulatorarm64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosx64/0.8.0/kotlinx-io-bytestring-watchosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosx64/0.8.0/kotlinx-io-bytestring-watchosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-io-bytestring-watchosx64/0.8.0/kotlinx-io-bytestring-watchosx64-0.8.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-io-bytestring-watchosx64",
        "version": "0.8.0"
      }
    }
  ]
}
