{
  "formatVersion": "1.1",
  "component": {
    "group": "com.electronwill.night-config",
    "module": "core",
    "version": "3.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-3.8.2.jar",
          "url": "core-3.8.2.jar",
          "size": 380967,
          "sha512": "6a4540148b1272b34a0ebffb5348eb407060d7471f156bf52e843210c4cca1c99e6324a71ddc473b2936f0730fca0c76e18eb982f6e7d51c099901cb6fe9d276",
          "sha256": "389d9b25bbaa794dd31c8c3e6e00f1a229d638333521b8ac0b4ec5a28a4e9bf3",
          "sha1": "94eee571e1524129804d08c75f6416a3be380ad4",
          "md5": "d6a1f12dee450edefaadb23275828947"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.8.2.jar",
          "url": "core-3.8.2.jar",
          "size": 380967,
          "sha512": "6a4540148b1272b34a0ebffb5348eb407060d7471f156bf52e843210c4cca1c99e6324a71ddc473b2936f0730fca0c76e18eb982f6e7d51c099901cb6fe9d276",
          "sha256": "389d9b25bbaa794dd31c8c3e6e00f1a229d638333521b8ac0b4ec5a28a4e9bf3",
          "sha1": "94eee571e1524129804d08c75f6416a3be380ad4",
          "md5": "d6a1f12dee450edefaadb23275828947"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.8.2-javadoc.jar",
          "url": "core-3.8.2-javadoc.jar",
          "size": 586259,
          "sha512": "558e6c5a2da1e054dff1ad2ef506c41e445d8dcee14ca318cc8ca19c6e1994e9a4360df7fdae2d5bd758aacf8c09c892722e0f086de1ec08080eeed1e1f9fceb",
          "sha256": "32a9ae91be8dfd23ca62b3c77ed6982bb03216e0655a372c0ca45f77c1a086e7",
          "sha1": "aa38f89d7fbea0e25652ffd6b78aa9d8826929ae",
          "md5": "311c5feb6e9ab6f611a4cb40321b6753"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.8.2-sources.jar",
          "url": "core-3.8.2-sources.jar",
          "size": 196492,
          "sha512": "04bb920ebf9aabbb737c1f12a986469725be4176e58b05990834c66314528f6a64312c8fa89323dc6748598a3d84fabb858f6e13b8118b1744aa9efc7166a3dc",
          "sha256": "ac511b2f8bfcac738dc362cda3ddc35096ef14a1fc0ac6860af298aa761d7008",
          "sha1": "a10239f9272f4e33ef1995f01ccae5b0497a012b",
          "md5": "7c38792f0ae8a12111365db039af8741"
        }
      ]
    }
  ]
}
